### PR TITLE
cockroachdb: fork sentry-go, also make the inAppFrame logic customizable

### PR DESCRIPTION
**Pull request by knz**
2nd commit inspired from https://github.com/cockroachdb/raven-go/pull/1, needed for CockroachDB.

@tooolbox can you also review this?

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/sentry-go/1)

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/sentry-go/1)* status: all files reviewed, 1 unresolved discussion (waiting on @dt and @knz)

___
*[in_app.go, line 9 at r1](https://reviewable.io/reviews/cockroachdb/sentry-go/1#-LxClDHj5K3yG6Z23gI5:-LxClDHj5K3yG6Z23gI6:b-311p27) ([raw file](https://github.com/cockroachdb/sentry-go/blob/f0f24a431a73886188e15eae4eea6423b4c03841/in_app.go#L9)):*
> ```Go
> 
> func isInAppFrame(frame Frame) bool {
> 	if frame.Module == "main" {
> ```

What is the reason for this condition?

**Review by tooolbox — COMMENTED** [review]
Will do!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/sentry-go/1#-:-LxCvSMwC-Tmt1oo2PI8:bhy9ost)* status: all files reviewed, 2 unresolved discussions (waiting on @dt, @knz, and @yuzefovich)

___
*[in_app.go, line 9 at r1](https://reviewable.io/reviews/cockroachdb/sentry-go/1#-LxClDHj5K3yG6Z23gI5:-LxCstWu7AFQoSw59XiT:b7peo3u) ([raw file](https://github.com/cockroachdb/sentry-go/blob/f0f24a431a73886188e15eae4eea6423b4c03841/in_app.go#L9)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

What is the reason for this condition?
</blockquote></details>

Anything in package `main` would always be considered in-app, without further thought.
___
*[in_app.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/sentry-go/1#-LxCtOGx1JMBYrq7JRTB:-LxCtOGx1JMBYrq7JRTC:b-dvi3jx) ([raw file](https://github.com/cockroachdb/sentry-go/blob/f0f24a431a73886188e15eae4eea6423b4c03841/in_app.go#L20)):*
> ```Go
> 	if strings.HasPrefix(frame.AbsPath, build.Default.GOROOT) ||
> 		strings.Contains(frame.Module, "vendor") ||
> 		strings.Contains(frame.Module, "third_party") {
> ```

Minor, do you want to change these to `/vendor/` and `/third_party/` as mentioned in [another thread](https://github.com/cockroachdb/raven-go/pull/3#issuecomment-554641240)?  It was a good idea, and the move to sentry-go is significant enough that any behavioral changes connected with this would be acceptable.
___
*[in_app.go, line 34 at r1](https://reviewable.io/reviews/cockroachdb/sentry-go/1#-LxCuonF9c_i8pt2QcYw:-LxCuonF9c_i8pt2QcYx:b-6b8gyv) ([raw file](https://github.com/cockroachdb/sentry-go/blob/f0f24a431a73886188e15eae4eea6423b4c03841/in_app.go#L34)):*
> ```Go
> func RegisterInAppFrameFn(fn func(Frame) bool) {
> 	isInAppFrameFn = fn
> }
> ```

BTW, smart.

**Review by tooolbox — COMMENTED** [review]
Tests are fine:
```sh
me@iMac ~/g/sentry-go-knz> go test ./...
ok  	github.com/getsentry/sentry-go	0.058s
?   	github.com/getsentry/sentry-go/echo	[no test files]
?   	github.com/getsentry/sentry-go/example/basic	[no test files]
?   	github.com/getsentry/sentry-go/example/echo	[no test files]
?   	github.com/getsentry/sentry-go/example/fasthttp	[no test files]
?   	github.com/getsentry/sentry-go/example/flush	[no test files]
?   	github.com/getsentry/sentry-go/example/gin	[no test files]
?   	github.com/getsentry/sentry-go/example/http	[no test files]
?   	github.com/getsentry/sentry-go/example/iris	[no test files]
?   	github.com/getsentry/sentry-go/example/martini	[no test files]
?   	github.com/getsentry/sentry-go/example/multiclient	[no test files]
?   	github.com/getsentry/sentry-go/example/negroni	[no test files]
?   	github.com/getsentry/sentry-go/example/recover	[no test files]
?   	github.com/getsentry/sentry-go/example/synctransport	[no test files]
?   	github.com/getsentry/sentry-go/example/with_extra	[no test files]
?   	github.com/getsentry/sentry-go/fasthttp	[no test files]
?   	github.com/getsentry/sentry-go/gin	[no test files]
?   	github.com/getsentry/sentry-go/http	[no test files]
?   	github.com/getsentry/sentry-go/iris	[no test files]
?   	github.com/getsentry/sentry-go/martini	[no test files]
?   	github.com/getsentry/sentry-go/negroni	[no test files]
```

I'll note that `go test all -short` produces a metric ton of errors across many packages, but master on `sentry-go` is in the same position.  I get the feeling that method of running tests may not be as applicable for Go Modules projects.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/sentry-go/1#-:-LxCyOVl6d4NkBrdDScC:bqju5jl)* status: all files reviewed, 2 unresolved discussions (waiting on @dt, @knz, and @yuzefovich)

**Comment by dt** [comment]
I have no opinions on this, but I'm curious what motivated the switch to a new import path -- we've forked libraries (including this one) in the past and kept the import path the same, just changing remote path to point to our fork, right?

**Comment by knz** [comment]
The import path has to change to support running the tests in this package and using it out of tree with go mod.
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/sentry-go/1)* status: all files reviewed, 1 unresolved discussion (waiting on @dt and @yuzefovich)

___
*[in_app.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/sentry-go/1#-LxCtOGx1JMBYrq7JRTB:-LxMMzrV4zGXhuTi_ubC:b-896fix) ([raw file](https://github.com/cockroachdb/sentry-go/blob/f0f24a431a73886188e15eae4eea6423b4c03841/in_app.go#L20)):*
<details><summary><i>Previously, tooolbox (Matt Mc) wrote…</i></summary><blockquote>

Minor, do you want to change these to `/vendor/` and `/third_party/` as mentioned in [another thread](https://github.com/cockroachdb/raven-go/pull/3#issuecomment-554641240)?  It was a good idea, and the move to sentry-go is significant enough that any behavioral changes connected with this would be acceptable.
</blockquote></details>

Done.

**Pull request merged**
